server:
  port: 8081
api:
  internal-services:
    transaction-api:
      base-url: http://localhost:8082/domain-services/
      time-out: 3000
info:
  app:
    name: Transaction service
    description: Api orquestador de transacciones
    version: 1.0.0
#debug: true

